plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.djonpanch.bankir'
    compileSdk 34

    defaultConfig {
        applicationId "ru.djonpanch.bankir"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.4"
    }

    signingConfigs {
        release {
            storeFile file("../keystore/release.keystore")
            storePassword "zakupki2026"
            keyAlias "zakupki"
            keyPassword "zakupki2026"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
